# Генерация случайных значений и комбинаторика

Модуля для генерации случайных значений:
* модуль random
* numpy.random
* scipy.stats

Сравнение разных способов:
1. Встроенный модуль `random` vs `numpy.random`
   1. Основаны на разных генераторах (MT19937 для random и PCG64 для numpy.random)
   2. Во многом схожи, у numpy генератора больше методов, быстрее генерирует большое количество значений и дает на выходе numpy массивы. 
2. Модуль `numpy.random` vs `scipy.stats`
   1. Scipy под капотом использует numpy.random, но знает больше различных распределений. Более подробно описаное в [distributions.ipynb](distributions.ipynb)


## Numpy.random

Начиная с версии 1.17 (2019 год) предпочительным способо использования является создание экзмепляра класса `Generator` вызовом метода `np.random.default_rng()` и использование различных методов этотго класса для генерации случайных значений.

[Список методов](https://numpy.org/doc/stable/reference/random/generator.html)

In [64]:
import numpy as np
np.set_printoptions(legacy="1.25")
rng = np.random.default_rng()

print("Integers:", rng.integers(low=0, high=10, size=5))
print("Floats [0.0, 1.0):", rng.uniform(low=0.0, high=1.0, size=5))
print("Normal distribution (mean=0, std=1):", rng.normal(loc=0.0, scale=1.0, size=5))
print("Random choice from array:", rng.choice(['apple', 'banana', 'cherry'], size=5))
print("Random permutation of array:", rng.permutation([1, 2, 3, 4, 5]))


Integers: [2 4 6 0 9]
Floats [0.0, 1.0): [0.93141018 0.5284698  0.48427996 0.48775773 0.24912085]
Normal distribution (mean=0, std=1): [ 0.1918961  -0.09142838  1.02079859  1.83484805  0.86225244]
Random choice from array: ['apple' 'banana' 'cherry' 'cherry' 'apple']
Random permutation of array: [3 5 1 4 2]


**Перемешивание массивов**

Для перемешивания массивов имеется 3 метода:
1. `shuffle` - перемешивает inplace
2. `permutation` - перемешивает и создаёт копию
3. `permuted` - перемешивает. может делать inplace, может создавать копию.

Важным отличием первых двух от третьего является то, что для многомерных массивов перемешивание происходит целиком по строчкам/столбцам (меняется порядок их следования, но не порядок элементов внутри), тогда как третий метод перемешивает значения внутри строк/столбцов, не меняя их порядок.

In [20]:
rng = np.random.default_rng()

x = rng.integers(10, size=15).reshape(3, 5)
x

array([[4, 6, 0, 1, 7],
       [2, 2, 1, 4, 6],
       [4, 8, 6, 4, 1]])

In [21]:
rng.permutation(x, axis=0)

array([[2, 2, 1, 4, 6],
       [4, 8, 6, 4, 1],
       [4, 6, 0, 1, 7]])

In [22]:
rng.permuted(x, axis=0)

array([[4, 8, 6, 4, 1],
       [2, 2, 0, 1, 7],
       [4, 6, 1, 4, 6]])

## Комбинаторика

Чтобы просто посчитать количество способов используем методы из модуля `scipy.special`, если хотим получить сами наборы элементов, то используем методы из модуля `itertools`

In [76]:
from itertools import combinations, permutations
from scipy.special import comb, perm

**Комбинации (combinations)** - выбор *k* элементов из набора *n* элементов, порядок неважен.

$C_n^k=\frac{n!}{(n-k)!k!}$

In [ ]:
# Простой случай одиночных значений
k, n = 3, 5
x = range(n)
print(f"Amount of combinations of {k} from {n}:", comb(n, k))
print(f"Combinations of {k} from {n}:", list(combinations(x, k)))

Amount of combinations of 3 from 5: 10.0
Combinations of 3 from 5: [(0, 1, 2), (0, 1, 3), (0, 1, 4), (0, 2, 3), (0, 2, 4), (0, 3, 4), (1, 2, 3), (1, 2, 4), (1, 3, 4), (2, 3, 4)]


In [75]:
# Наборы значений
k, n = [1,2,3,4,5], 5
print(f"Amount of combinations of {k} from {n}:", comb(n, k))
print(f"Combinations of {k[1]} from {n}:", list(combinations(x, k[1])))

Amount of combinations of [1, 2, 3, 4, 5] from 5: [ 5. 10. 10.  5.  1.]
Combinations of 2 from 5: [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]


**Перестановки (permutations)** - выбор *k* элементов из набора *n* элементов, порядок важен.

$A_n^k=\frac{n!}{(n-k)!}$

In [80]:
# Простой случай одиночных значений
k, n = 2, 5
x = range(n)
print(f"Amount of combinations of {k} from {n}:", perm(n, k))
print(f"Combinations of {k} from {n}:", list(permutations(x, k)))

Amount of combinations of 2 from 5: 20.0
Combinations of 2 from 5: [(0, 1), (0, 2), (0, 3), (0, 4), (1, 0), (1, 2), (1, 3), (1, 4), (2, 0), (2, 1), (2, 3), (2, 4), (3, 0), (3, 1), (3, 2), (3, 4), (4, 0), (4, 1), (4, 2), (4, 3)]


In [77]:
# Наборы значений
k, n = [1,2,3,4,5], 5
print(f"Amount of combinations of {k} from {n}:", perm(n, k))
print(f"Combinations of {k[1]} from {n}:", list(permutations(x, k[1])))

Amount of combinations of [1, 2, 3, 4, 5] from 5: [  5.  20.  60. 120. 120.]
Combinations of 2 from 5: [(0, 1), (0, 2), (0, 3), (0, 4), (1, 0), (1, 2), (1, 3), (1, 4), (2, 0), (2, 1), (2, 3), (2, 4), (3, 0), (3, 1), (3, 2), (3, 4), (4, 0), (4, 1), (4, 2), (4, 3)]
